spring:
  redis:
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASS:du58M6RcqI}
    host: ${REDIS_HOST:redis-headless.redis-test.svc}
    ssl: false
    timeToLive: 60
    mode: standalone
    
management:
  endpoints:
    web:
      exposure:
        include: health, info