---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redisdemo-enhance
  name: redisdemo-enhance
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisdemo-enhance
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redisdemo-enhance
    spec:
      containers:
      - image: quay.io/zhangchl007/redisdemo:v3-enhance
        imagePullPolicy: Always
        name: redisdemo-enhance
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: REDIS_HOST
            value: redis-headless.redis-test.svc
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASS
            value: du58M6RcqI
---
apiVersion: v1
kind: Service
metadata:
  name: redisdemo-enhance
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: redisdemo-enhance
  type: LoadBalancer
